apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: doodle-back
  name: doodle-back
  namespace: doodle-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: doodle-back
  template:
    metadata:
      labels:
        app: doodle-back
    spec:
      containers:
      - name: api
        image: localhost:32000/api:latest
        ports:
        - containerPort: 80
      - name: etherpad
        image: localhost:32000/etherpad:latest
        ports:
        - containerPort: 9001
      - name: mysql
        image: localhost:32000/mysql:latest
        ports:
        - containerPort: 3306
        env: 
        - name: MYSQL_ROOT_PASSWORD
          value: ""
        args: 
          - ./application
          - -Dquarkus.http.host=0.0.0.0
          - -Dquarkus.datasource.username=root
          - -Dquarkus.datasource.password=
          - -Dquarkus.datasource.jdbc.url=jdbc:mysql://doodle-mysql:3306/tlc?useUnicode=true&characterEncoding=utf8&useSSL=false
          - -Dquarkus.http.cors=true
          - -Dquarkus.http.cors.methods=GET,PUT,POST,DELETE,PATCH,OPTIONS
          - -Dquarkus.http.cors.headers=accept,origin,authorization,content-type,x-requested-with
          - -Dquarkus.http.cors.exposed-headers=Content-Disposition            
          - -Dquarkus.http.cors.access-control-max-age=24H
          - -Dquarkus.mailer.from=olivier.barais@univ-rennes1.fr
          - -Dquarkus.mailer.host=maildev
          - -Dquarkus.mailer.port=1025
          - -Dquarkus.mailer.ssl=false  
          - -Dquarkus.http.host=0.0.0.0
          - -Ddoodle.internalPadUrl=http://doodle-etherpad:9001
          - -Ddoodle.externalPadUrl=http://pad.tlc.fr/

