apiVersion: v1
kind: Service
metadata:
  name: doodle-back
  namespace: doodle-back
spec:
  selector:
    app: doodle-back
  ports:
  - name: api
    port: 80
    targetPort: 80
  - name: etherpad
    port: 9001
    targetPort: 9001
  - name: mysql
    port: 3306
    targetPort: 3306
  - name: smtp
    port: 25
    targetPort: 25
